# Generated by Django 6.1 on 2026-08-18 10:19

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('stored_name', models.CharField(max_length=64, unique=True, verbose_name='Имя файла на диске')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание')),
                ('link_token', models.CharField(default=storage.models.generate_link_token, max_length=64, unique=True, verbose_name='Токен специальной ссылки')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
